title: Connectivity Business Systems
email: cdupree@cbs-biz.com
description: > # CBS is a family owned and operated business serving the
  Central FL community and beyond for over twenty five years; providing
  copiers, digital imaging, and IT support.
keywords: "CBS,Connectivity Business Systems,Titusville,FL,Copiers,Ink,Toner,Digital Imaging,Laserfiche,Office Equipment,Managed Services"
url: "http://cbs-biz.com"
gems: [jekyll-paginate]
paginate: 5
collections:
  multi-function-products:
    output: true
  ink_toner:
    output: true
  team:
    output: false

defaults:
  - scope:
      path: ""
      type: multi-function-products
    values:
      banner: banner-products.jpg
  - scope:
      path: ""
      type: ink_toner
    values:
      banner: banner-ink_toner.jpg
  - scope:
      path: ""
      type: posts
    values:
      banner: banner-mountains.jpg
      permalink: content/:title

# Build settings
markdown: kramdown
